#src/USMB/SNMPBundle/Resources/config/routing.yml

#dashboard
usmbsnmp_dashboard:
    path:     /
    defaults: { _controller: USMBSNMPBundle:EasySNMP:dashboard }

#dashboard data
usmbsnmp_start_consumer:
    path:     /Consumer/Start/{id}
    defaults: { _controller: USMBSNMPBundle:EasySNMP:startConsumer }

#dashboard start consumer
usmbsnmp_stop_consumer:
    path:     /Consumer/Stop/{id}
    defaults: { _controller: USMBSNMPBundle:EasySNMP:stopConsumer }

#dashboard rabbitmq server data api
usmbsnmp_dashboard_data:
    path:     /data/dashboard
    defaults: { _controller: USMBSNMPBundle:EasySNMP:dashboardData }

#dashboard devices infos api
usmbsnmp_alerts_data:
    path:     /data/alerts
    defaults: { _controller: USMBSNMPBundle:EasySNMP:alertsData }

#mlaunch monitoring
usmbsnmp_monitor:
    path:     /monitor
    defaults: { _controller: USMBSNMPBundle:EasySNMP:monitor }

#devices
usmbsnmp_devices:
    path:     /Devices
    defaults: { _controller: USMBSNMPBundle:EasySNMP:devices }

#device
usmbsnmp_device:
    path:     /Device/{id}
    defaults: { _controller: USMBSNMPBundle:EasySNMP:device }

#manage devices
usmbsnmp_manage_devices:
    path:     /Manage/Devices
    defaults: { _controller: USMBSNMPBundle:EasySNMP:manageDevices }

#manage devices download file
usmbsnmp_manage_devices_download_config_file:
    path:     /Manage/Devices/download
    defaults: { _controller: USMBSNMPBundle:EasySNMP:exportJson }

usmbsnmp_manage_devices_upload_config_file:
    path:     /Manage/Devices/upload
    defaults: { _controller: USMBSNMPBundle:EasySNMP:importJson }

#manage device
usmbsnmp_manage_device:
    path:     /Manage/Device/{id}
    defaults: { _controller: USMBSNMPBundle:EasySNMP:manageDevice }

#delete device
usmbsnmp_delete_device:
    path:     /Delete/Device/{id}
    defaults: { _controller: USMBSNMPBundle:EasySNMP:deleteDevice }

#manage profiles
usmbsnmp_manage_profiles:
    path:     /Manage/Profiles
    defaults: { _controller: USMBSNMPBundle:EasySNMP:manageProfiles }

#manage profile
usmbsnmp_manage_profile:
    path:     /Manage/Profile/{id}
    defaults: { _controller: USMBSNMPBundle:EasySNMP:manageProfile }

#delete profile
usmbsnmp_delete_profile:
    path:     /Delete/Profile/{id}
    defaults: { _controller: USMBSNMPBundle:EasySNMP:deleteProfile }

#manage logs
usmbsnmp_manage_logs:
    path:     /Manage/Logs
    defaults: { _controller: USMBSNMPBundle:EasySNMP:manageLogs }

#manage users
usmbsnmp_manage_users:
    path:     /Manage/Users
    defaults: { _controller: USMBSNMPBundle:EasySNMP:manageUsers }

#manage user
usmbsnmp_manage_user:
    path:     /Manage/User/{id}
    defaults: { _controller: USMBSNMPBundle:EasySNMP:manageUser }

#delete user
usmbsnmp_delete_user:
    path:     /Delete/User/{id}
    defaults: { _controller: USMBSNMPBundle:EasySNMP:deleteUser }

