fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

usmbsnmp:
    resource: "@USMBSNMPBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
