<?php

namespace USMB\SNMPBundle\Repository;

/**
 * DeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceRepository extends \Doctrine\ORM\EntityRepository
{


    /**
     * @return int
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getNbHost()
    {
        $query = $this->createQueryBuilder('l');
        $query->select('COUNT(l)');

        return $query->getQuery()->getSingleScalarResult();
    }

    /**
     * @return int
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getNbHostOnline()
    {
        $query = $this->createQueryBuilder('l');
        $query
            ->where('l.isAlive = :param')
            ->setParameter('param', true)
            ->select('COUNT(l)');

        return $query->getQuery()->getSingleScalarResult();
    }

    /**
     * @return int
     */
    public function getNbRequestToSend()
    {
        $nbRequestToSend =0;

        $query = $this->createQueryBuilder('l');
        $query
            ->where('l.isAlive = :param')
            ->setParameter('param', true)
            ->select('l');

        $result = $query->getQuery()->getResult();

        foreach ($result as $device){
            foreach ($device->getProfiles() as $profile){
                $nbRequestToSend++;
            }
        }

        return $nbRequestToSend;
    }
}
