<?php

namespace USMB\SNMPBundle\Repository;

/**
 * Device_8_Profile_7Repository 
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Device_8_Profile_7Repository extends \Doctrine\ORM\EntityRepository
{
}
