<?php

namespace USMB\SNMPBundle\Repository;

/**
 * Device_1_Profile_3Repository 
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Device_1_Profile_3Repository extends \Doctrine\ORM\EntityRepository
{
}
