<?php

namespace USMB\SNMPBundle\Repository;

/**
 * Device_2_Profile_1Repository 
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Device_2_Profile_1Repository extends \Doctrine\ORM\EntityRepository
{
}
