<?php

namespace USMB\SNMPBundle\Repository;

/**
 * Device_7_Profile_5Repository 
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Device_7_Profile_5Repository extends \Doctrine\ORM\EntityRepository
{
}
