<?php

namespace USMB\SNMPBundle\Repository;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAll()
    {
        return $this->findBy(array(), array('createdAt' => 'DESC'));
    }
}
